/*
 * MundiAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MundiAPI.PCL;
using MundiAPI.PCL.Utilities;


namespace MundiAPI.PCL.Models
{
    public class CreateCardPaymentTokenRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string type;
        private Models.ApplePayRequest applePay;

        /// <summary>
        /// The authentication type
        /// </summary>
        [JsonProperty("type")]
        public string Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// The apple pay authentication request
        /// </summary>
        [JsonProperty("apple_pay")]
        public Models.ApplePayRequest ApplePay 
        { 
            get 
            {
                return this.applePay; 
            } 
            set 
            {
                this.applePay = value;
                onPropertyChanged("ApplePay");
            }
        }
    }
} 