/*
 * MundiAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MundiAPI.PCL;
using MundiAPI.PCL.Utilities;


namespace MundiAPI.PCL.Models
{
    public class GetBankTransferTransactionResponse : GetTransactionResponse 
    {
        // These fields hold the values for the public properties.
        private string url;
        private string bankTid;
        private string bank;
        private DateTime? paidAt;
        private int? paidAmount;

        /// <summary>
        /// Payment url
        /// </summary>
        [JsonProperty("url")]
        public string Url 
        { 
            get 
            {
                return this.url; 
            } 
            set 
            {
                this.url = value;
                onPropertyChanged("Url");
            }
        }

        /// <summary>
        /// Transaction identifier for the bank
        /// </summary>
        [JsonProperty("bank_tid")]
        public string BankTid 
        { 
            get 
            {
                return this.bankTid; 
            } 
            set 
            {
                this.bankTid = value;
                onPropertyChanged("BankTid");
            }
        }

        /// <summary>
        /// Bank
        /// </summary>
        [JsonProperty("bank")]
        public string Bank 
        { 
            get 
            {
                return this.bank; 
            } 
            set 
            {
                this.bank = value;
                onPropertyChanged("Bank");
            }
        }

        /// <summary>
        /// Payment date
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("paid_at")]
        public DateTime? PaidAt 
        { 
            get 
            {
                return this.paidAt; 
            } 
            set 
            {
                this.paidAt = value;
                onPropertyChanged("PaidAt");
            }
        }

        /// <summary>
        /// Paid amount
        /// </summary>
        [JsonProperty("paid_amount")]
        public int? PaidAmount 
        { 
            get 
            {
                return this.paidAmount; 
            } 
            set 
            {
                this.paidAmount = value;
                onPropertyChanged("PaidAmount");
            }
        }
    }
} 