/*
 * MundiAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using MundiAPI.PCL;
using MundiAPI.PCL.Utilities;

namespace MundiAPI.PCL.Models
{
    class GetTransactionResponseCreationConverter : JsonCreationConverter<GetTransactionResponse>
    {
        public GetTransactionResponseCreationConverter()
        {
            typeName = "transaction_type";
            dic = new System.Collections.Generic.Dictionary<string, System.Type>()
            {
                { "bank_transfer",typeof(GetBankTransferTransactionResponse)},
                { "debit_card",typeof(GetDebitCardTransactionResponse)},
                { "voucher",typeof(GetVoucherTransactionResponse)},
                { "boleto",typeof(GetBoletoTransactionResponse)},
                { "cash",typeof(GetCashTransactionResponse)},
                { "safetypay",typeof(GetSafetyPayTransactionResponse)},
                { "credit_card",typeof(GetCreditCardTransactionResponse)},
            };
        }
    }
}