/*
 * MundiAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MundiAPI.PCL;
using MundiAPI.PCL.Utilities;


namespace MundiAPI.PCL.Models
{
    public class RecipientsDefaultBankAccountRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.BankAccount1 bankAccount;
        private string paymentMode;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bank_account")]
        public Models.BankAccount1 BankAccount 
        { 
            get 
            {
                return this.bankAccount; 
            } 
            set 
            {
                this.bankAccount = value;
                onPropertyChanged("BankAccount");
            }
        }

        /// <summary>
        /// Payment mode
        /// </summary>
        [JsonProperty("payment_mode")]
        public string PaymentMode 
        { 
            get 
            {
                return this.paymentMode; 
            } 
            set 
            {
                this.paymentMode = value;
                onPropertyChanged("PaymentMode");
            }
        }
    }
} 