/*
 * MundiAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MundiAPI.PCL;
using MundiAPI.PCL.Utilities;


namespace MundiAPI.PCL.Models
{
    public class UpdateSubscriptionDueDaysRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int boletoDueDays;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("boleto_due_days")]
        public int BoletoDueDays 
        { 
            get 
            {
                return this.boletoDueDays; 
            } 
            set 
            {
                this.boletoDueDays = value;
                onPropertyChanged("BoletoDueDays");
            }
        }
    }
} 